name: build and push fourkeys event-handler and parser images to artifact registry

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  APP: fourkeys
  GAR_LOCATION: us
  GAR_REPOSITORY: sw-delivery-perf-prod
  GCP_PROJECT_ID: moz-fx-sw-delivery-perf-prod
  REF: ${{ github.ref_name }}

jobs:
  build_parser_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [argocd, circleci, github, pagerduty]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - id: gcp-auth
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          service_account: artifact-writer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}

      - uses: docker/login-action@v2
        name: Docker login
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}

      - name: build ${{ matrix.context }} parser image
        id: build-and-push-parser
        uses: docker/build-push-action@v3
        with:
          context: bq-workers/${{ matrix.context }}-parser
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ matrix.context }}-parser:${{ env.REF }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  build_event_handler_image:
    name: Build Four Keys container images
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - id: gcp-auth
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          service_account: artifact-writer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}

      - uses: docker/login-action@v2
        name: Docker login
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}

      - id: build-and-push-event-handler
        uses: docker/build-push-action@v3
        with:
          context: event-handler/
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/event-handler:${{ env.REF }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

